### ISSUE TITLE
Minor fixes

### ISSUE THREAD

**Issue by therealcoder1337** [quaffui/quaff#35]
1. For the Layout with `view="lHh Lpr lFf"`, the right part of the QHeader becomes hidden once the drawer is opened. It can be fixed with a SCSS like:

```scss
.q-drawer--active ~ .q-header {
    $drawer-width: 300px;
    width: calc(100% - $drawer-width);
}
```
2. We should change the body class indicating light or dark mode to `body--light` and `body--dark`, respectively.
